FROM golang:1.12.5 as builder
WORKDIR /programs
COPY . /programs
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o websocket_client ./src/websocket_client/cmd/main.go
EXPOSE 8080
CMD ["./websocket_client"]
